const CONFIG = Object.freeze({
  VERSION: '1.0.0',
  VERSION_NOTICE: '2026-09-27',
  MODELE_SIMULATION: 'gemini-3.5-flash-lite',
  MODELE_EVALUATION: 'gemini-3.8-flash',
  MODELE_GENERATION: 'gemini-3.8-flash',
  URL_API_IA: 'https://generativelanguage.googleapis.com/v1beta/models/',
  TAILLE_MAX_REQUETE: 60000,
  SESSION_DUREE_MAX_MIN: 480,
  SESSION_INACTIVITE_MIN: 30,
  SESSIONS_MAX: 5,
  ECHECS_MAX: 5,
  VERROU_MIN: 15,
  STRESS_INITIAL: 60,
  STRESS_INFRACTION: 20,
  VARIATION_MAX: 20,
  PENALITE_PAR_SORTIE: 2,
  PENALITE_MAX: 8,
  MESSAGE_FLASH_DECLENCHEUR: 3,
  DUREE_FLASH_S: 30,
  TOLERANCE_FLASH_S: 5,
  TOLERANCE_FIN_S: 15,
  APPELS_SUPPLEMENTAIRES_MAX: 4,
  DEMARRAGES_MAX_PAR_HEURE: 30,
  APPELS_IA_MAX_PAR_JOUR: 400,
  CONSERVATION_DEFAUT_JOURS: 180,
  CONSERVATION_MIN_JOURS: 30,
  CONSERVATION_MAX_JOURS: 365,
  DUREE_TEST_MIN: 10,
  DUREE_TEST_MAX: 180,
  QCM_MIN: 2,
  QCM_MAX: 6,
  QUESTIONS_MAX: 3,
  REPLIQUES_MIN: 4,
  REPLIQUES_MAX: 10,
  LONGUEUR: Object.freeze({
    intitule: 80,
    entreprise: 60,
    profil: 2000,
    libre: 40,
    libresMax: 5,
    nom: 60,
    reponseCourte: 600,
    reponseLongue: 5000,
    messageIA: 600,
    motif: 120,
    enonce: 400,
    choix: 160,
    critere: 160,
    persona: 600,
    faits: 1200,
    email: 120,
    cellule: 60
  }),
  SECTEURS: Object.freeze({
    fintech: 'Fintech (mobile money)',
    agro: 'Agroalimentaire',
    ong: 'Humanitaire (ONG)',
    autre: 'Autre secteur'
  }),
  COMPETENCES: Object.freeze([
    { id: 'empathie', libelle: 'Empathie et écoute active', type: 'soft' },
    { id: 'gestion_crise', libelle: 'Gestion de crise', type: 'soft' },
    { id: 'communication', libelle: 'Communication claire et structurée', type: 'soft' },
    { id: 'negociation', libelle: 'Négociation et recherche de solution', type: 'soft' },
    { id: 'management', libelle: 'Management et leadership d\'équipe', type: 'soft' },
    { id: 'analyse_chiffres', libelle: 'Analyse de données chiffrées', type: 'hard' },
    { id: 'procedures', libelle: 'Respect des procédures et de la conformité', type: 'hard' },
    { id: 'resolution', libelle: 'Résolution de problème opérationnel', type: 'hard' }
  ])
});
